version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.20.0-20240402
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.20.0-20240402
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  tests:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
    volumes:
      - ./report.html:/app/report.html
